name: Fastlane Releases
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  google-play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          version_number=$(cat version.yml | sed 's/\(---\|major: \|minor: \|patch: \|\)//g' | sed -z 's/\n/./g;s/,$/\n/' | sed 's/^\.//g' | sed 's/\.$//g' )
          echo "${version_number}"
          echo "version_number=${version_number}" >> $GITHUB_ENV
          echo "${{ env.version_number }}"
      - run: |
          version_code=$(cat pubspec.yaml | grep "version:" | sed 's/version:.*+//g')
          echo "version_code=${version_code}" >> $GITHUB_ENV
          echo "${{ env.version_code }}"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > android/key.jks
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> android/key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> android/key.properties
          echo "storeFile=../key.jks" >> android/key.properties
          cat android/key.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      - name: Create Google Play Config file
        run: |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > android/play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter build appbundle
      - run: flutter build apk
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version_number }}
          body: |
            Check git history
          draft: false
          prerelease: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
      - name: Deployment with Fastlane
        env:
          RUBYOPT: "-rostruct"
        run: |
          bundle install
          bundle exec fastlane update_plugins
          bundle exec fastlane beta
