name: Push to Dockerhub
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          version_number=$(cat version.yml | sed 's/\(---\|major: \|minor: \|patch: \|\)//g' | sed -z 's/\n/./g;s/,$/\n/' | sed 's/^\.//g' | sed 's/\.$//g' )
          echo "${version_number}"
          echo "version_number=${version_number}" >> $GITHUB_ENV
          echo "${{ env.version_number }}"
      - run: |
          version_code=$(cat pubspec.yaml | grep "version:" | sed 's/version:.*+//g')
          echo "version_code=${version_code}" >> $GITHUB_ENV
          echo "${{ env.version_code }}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.web
          push: true
          tags:
            - yonggan/kifferkarte:${{ env.version_number }}
            - yonggan/kifferkarte:latest
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Dockerfile.web
          push: true
          tags: ${{ env.version_number }}
          labels:
            - ${{ env.version_number }}
            - latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
